name: Deploy Lambdas

on:
  workflow_dispatch:

jobs:
  deploy_lambdas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambdas
        env: 
          LAMBDA_GET_URL: ${{ vars.LAMBDA_GET_URL }}
          LAMBDA_URL_SHORTENER: ${{ vars.LAMBDA_URL_SHORTENER }}
          LAMBDA_URL_SEND_CONTACT_EMAIL: ${{ vars.LAMBDA_SEND_CONTACT_EMAIL }}
          LAMBDA_IP_VISITOR_COUNTER: ${{ vars.LAMBDA_IP_VISITOR_COUNTER }}
        run: npm run deploy:lambdas
