name: Build & Deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          pip install pygame pygbag

      - name: Build all games
        run: |
          echo "Setting up Emscripten environment..."
          source ./emsdk/emsdk_env.sh
          
          echo "Rebuilding all games..."
          npm run clean-games
          npm run build-games

      - name: Build frontend
        run: |
          echo "Building react app..."
          npm run build

      - name: Tree check
        run: tree ./public -I node_modules

      - name: Deploy
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

        run: | 
          echo "Deploying files to S3..."
          npm run deploy   
          echo "Done!"
